name: Publish to GH Pages
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Checkout destination
        uses: actions/checkout@v3
        if: github.ref == 'refs/heads/main'
        with:
          ref: gh-pages
          path: built-site

      - name: Setup Hugo
        run: |
          curl -L -o /tmp/hugo.tar.gz 'https://github.com/gohugoio/hugo/releases/download/v0.125.7/hugo_extended_0.125.7_linux-amd64.tar.gz'
          tar -C ${RUNNER_TEMP} -zxvf /tmp/hugo.tar.gz hugo

      - name: Build
        run: ${RUNNER_TEMP}/hugo

      - name: Clean destination directory
        if: github.ref == 'refs/heads/main'
        run: |
          rm -rf ${GITHUB_WORKSPACE}/built-site/*

      - name: Copy built site
        if: github.ref == 'refs/heads/main'
        run: |
          cp -R public/* ${GITHUB_WORKSPACE}/built-site/

      - name: Deploy
        if: github.ref == 'refs/heads/main'
        run: |
          cd ${GITHUB_WORKSPACE}/built-site
          git add .
          if [ -n "$(git status --porcelain)" ]; then
            git config user.name 'Theskrtnerd'
            git config user.email 'tvbbd2@gmail.com'
            git commit -m 'Updated site'
            git push
          else
            echo "No changes to commit"
          fi
